// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3qGygN-FgG9IGXb1UDFBkO_2bDVvQgeg',
    appId: '1:12152361848:web:772c23584c1490e4516e8d',
    messagingSenderId: '12152361848',
    projectId: 'taller-movil-491200',
    authDomain: 'taller-movil-491200.firebaseapp.com',
    storageBucket: 'taller-movil-491200.firebasestorage.app',
    measurementId: 'G-1Z4DLFNBQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHP-XG-m6uAUpr1hkO-F6xNIkr9PgI3Kw',
    appId: '1:12152361848:android:b648765d3bff0e83516e8d',
    messagingSenderId: '12152361848',
    projectId: 'taller-movil-491200',
    storageBucket: 'taller-movil-491200.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTpCl7_jxp6XaVc5FnwRHuJIlT4-PI-0c',
    appId: '1:12152361848:ios:593e621a1b3a4116516e8d',
    messagingSenderId: '12152361848',
    projectId: 'taller-movil-491200',
    storageBucket: 'taller-movil-491200.firebasestorage.app',
    iosBundleId: 'com.example.xtremePerformance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTpCl7_jxp6XaVc5FnwRHuJIlT4-PI-0c',
    appId: '1:12152361848:ios:593e621a1b3a4116516e8d',
    messagingSenderId: '12152361848',
    projectId: 'taller-movil-491200',
    storageBucket: 'taller-movil-491200.firebasestorage.app',
    iosBundleId: 'com.example.xtremePerformance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3qGygN-FgG9IGXb1UDFBkO_2bDVvQgeg',
    appId: '1:12152361848:web:f9c3c288f2045e44516e8d',
    messagingSenderId: '12152361848',
    projectId: 'taller-movil-491200',
    authDomain: 'taller-movil-491200.firebaseapp.com',
    storageBucket: 'taller-movil-491200.firebasestorage.app',
    measurementId: 'G-LSV9813V5R',
  );
}
